# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1SxOTQ8GwSowWd8nfFedlZmNO0bNT+tzVk4B1UEJSNUvMPYQgyIIVhm4VgMRCo8TRbRQMontFO76bvPsnIBZUcSBxYqJs04c+gSmmTPrnb+qYASjWG24eAgDFif36V2ESZ/Nx+ECALbNM792uOizEeigbQ275tfbi8x0FJurRgFFDwADjzVy1Bc+ZDlhJR41h/A1MFbvnY2WNbr96XGjWJY6NYQNX2nyi/Oco+yRq70BlHkIRA==,iv:e+9TPuJPa71ZrU55wu4M+P4oO+YbuJcTL5hGEKzXGcY=,tag:SeVdRmxVS2vKIHegXtZUmw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1mf528d4zgyekad0gdzz3aknctp6er0vw2zkxm0rv2l0sy5fudpdqr3m6c0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUTIrOXU0bk5qTHJ3K2Jm
        cm15ZzhIWFlWYmNlYkkrRURVWjdLOCs5TGdNCnpFVTZHdlhQd1RveEFwenpZN3FY
        VE5wSTVmMVB5SGp2MnE0QXdMMXREZW8KLS0tIEQvN2duTEJLVTZQRzFFVDBwN25E
        NFhIVHJaWU5CeGVLdU4wY3lSUGloSVUKkM+vytmOBObx9iDE97K3g+gjMm77C6Hj
        sSXQWKheKe8ZhJKtj4PZ37B5GnmamsaYLf+r55TwqvPl1HmIzLLG5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T12:59:14Z"
  mac: ENC[AES256_GCM,data:6kK7FZhxC8GreXwYqk5/xxHeTonIsFrBTgjUWihEI/cFzVqQracDov17aOqcyMytTAvUL5RWlhjwn+dAQBq7w/1TRsK4W+4u2cx+eZ//n8qKEkgUIzrvVEmkCLbvDbf92ZQmIQ3jqfCbhFfthP0w+s3Fovezsu6pCSEySFhscQo=,iv:MEb5fL+nHbLV4+f0CIOsQ8XGO1G9vEyV9v6tJwk/FBI=,tag:1+BJEGggOQ0/I51+MmwIlA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
