---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age12wnvdrx5d29llrm73c8vmj3wfk0sn9zeckenygdhgn5da0zm4c8sqa5auh"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age12wnvdrx5d29llrm73c8vmj3wfk0sn9zeckenygdhgn5da0zm4c8sqa5auh"
stores:
  yaml:
    indent: 2
