# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2ZOiNUcr2Ykay64B881kqzNybIWMcA0t96VCdD0tFA2ljfQROdOZYjg89x+5THeIkxBGnTamXK5+bqQ1dYQPGUjcJljY7R2kyqefDXCsbvvft9g1BOLnGg2L3UMtn6lzIez5RodkVP2+PW82knaAZHTljvigRbHqUBV0ex8jagQanssN/Hf3+yLHOCGRn4jSP9XfshIgAou35xEE7KTxZL1syMrOWVq0b69DtNuOT8i1VmLl,iv:AhQHBYBTaPYHKS6S+7AzhJF/euzKwoV/rEqqgFeHKg0=,tag:3F0khQb8BpqUPbU7bxIn4w==,type:str]
sops:
  age:
    - recipient: age12wnvdrx5d29llrm73c8vmj3wfk0sn9zeckenygdhgn5da0zm4c8sqa5auh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b2U1elJBT25ITTFMYkR5
        Y2xsZHRvQS9VWlZEQVZzTWhxWjIrN2VjTm04ClNrVkNNZzlWMGRBSmNCQ3k5K0xO
        YTQvdS9KR2pROTRVQyszZEM3d1ovYzQKLS0tIDhUeFRDQVF3OFBpNmp5bFROZ1d5
        eXJ6N0RrTVNVb1FSSjBoNzI3ZDNSRjgKD00/8qT35dfdk45Y4wic+FobprdDqwVd
        teyBNz6PlFG+FL/jnCy2bakh9SkM+BM/Y8EfVKTKfEiFmnSANqm3NQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-03T16:08:16Z"
  mac: ENC[AES256_GCM,data:ap4xUVGE0MVaZbO9E6La+l58PDePRCPhhkZO4tavIC5Cb23RsP+p6jlvQQSLSSXPiG9CReEkBbt0hEvgsENf2mwCh4e/yGaoLRSIVD7/FScbB9VqVpJ2aXrk2jSITD4uWmwF+CUkx0BPXacMCWiSh3PPlAfRbi/hvOuQCsmZPRE=,iv:icExO/XEbjz8Xfpj1DMqPmV2jVWOXHZcnQHOGhpN2U4=,tag:fUQgO1W+RNFGUWsXt7RT7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
