---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-gateway
  labels:
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/instance: k8s-gateway
rules:
  - apiGroups:
    - gateway.networking.k8s.io
    resources:
    - '*'
    verbs:
    - watch
    - list
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
