---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-gateway
  labels:
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/instance: k8s-gateway
rules:
    - apiGroups:
      - ""
      resources:
      - services
      - namespaces
      verbs:
      - list
      - watch
    - apiGroups:
      - extensions
      - networking.k8s.io
      resources:
      - ingresses
      verbs:
      - list
      - watch
    - apiGroups:
      - gateway.networking.k8s.io
      resources:
      - grpcroutes
      - httproutes
      - tlsroutes
      verbs:
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-gateway-binding
subjects:
  - kind: ServiceAccount
    name: k8s-gateway
    namespace: network
roleRef:
  kind: ClusterRole
  name: k8s-gateway
  apiGroup: rbac.authorization.k8s.io
