apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:knuVkY4pdEx1Pg==,iv:6di+m1Hc0yWmhdCWdOE2nB1MeA3siCF1Dneqh9PLfLA=,tag:PPnG57K16tcmMzPA1K7bBw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1mf528d4zgyekad0gdzz3aknctp6er0vw2zkxm0rv2l0sy5fudpdqr3m6c0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZkt0dmZiWUVNc2N3WmRG
        WXJyZUhtN3lITTdXd3c3Wk1RcnBHUmNBMUF3CkFNQmRkbG81RjIxUEduWjYwbFkv
        alIxQjJWRy9qU1JyTmJvN2xlVXR5cmsKLS0tIGtYcEl0dG1uYS9kZGxPbkFmNVV6
        N1pNdlkyMG85NEVLdUgwVzc0QUg2S1kK6MuZJvG+bgE9vsUnb053RgXHx/fFT+GO
        mDFVVnqfobMM5h+1m0BvqY3WHWTxHxbOGPYRyf52FbPsZzqDju9D/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T12:59:13Z"
  mac: ENC[AES256_GCM,data:/qG1bd1tpxpU7Kj7A6SqxyGi3fMvihqp0E/FGqNi5XfWgEkBCG61XMkRLkI2FiZ6AOnQ4/51atBFBArKUAbmoT/0ZQwiIGzBLOYx5g4nxjLUjqukaDbcgEKO8+e6ALH1Bwg/NHuWE8uURTVOj8ITU+TOGyucSfgl48R/HlgVoW0=,iv:PShxrBfeA7oUvQFGARfc2Sd5K/yMqsBaVFoGHLlppWo=,tag:NPKnmrBsG46GEuJddyu8zA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
