# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:D0O4MbVY/3vs7eIjevA399YwfS9At52CXfTM+fasfVpNt+0exqs=,iv:QDE0wE//JbLrTcYEGcMKHhwsM0S9UEs92Kj8XhmxGjc=,tag:vf8VYS4AoPX4+kKpk1YJsw==,type:str]
sops:
  age:
    - recipient: age1u7f7jaaq9x8ju7zdxf74scu8xg5ulwhlwy72lzppq5hhuxthc50stmx7m4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Wjg0R0RWV09QaFRCSVJW
        RFBmK3VpSnRCREZ4SmxDbEt6dGNVUysrZ2l3ClVMSDNYYnI3MXdhUXBRRnY1MkF5
        R3kwSC9weFoxc29CTmE2eFFQR3kxdjAKLS0tIG0rZlZ1YzRMckxDYVhLU3VOZEsz
        V3dWcWJJRmVmM2FqaG14Tm5ZbGVKcUUKoD2NFyehw4Rsh+grtKnYzFfnlLoxLpDk
        QNS23YvA9gvijYKaevFsRH1gUI8ZGBPy3d0iBc7kFohQv5ixgjDwkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-03T19:15:33Z"
  mac: ENC[AES256_GCM,data:3L26Pm6vFdD4MN2UiR3pKNlza/eUoh9viJIBFvUia/L552QCbAK69RHcT/g7rPrx41XYA/rFHNheP65slS+OxDRu3Ln8PUr+VX1u6cuUvbl0yeImY9NuU0EBnyKz40mLZURCjOhNVoGez2ZCZalPUPPETPpTGnwbK8FXsBYXUKY=,iv:RWt9WAWOhTgwpQpgfP25wUlCkBPwL4xIvZu8oPT01PA=,tag:QUdlHnvaLXqcu9ks8r6BWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
