---
crds:
  enabled: true
  upgradeJob:
    enabled: true
    forceConflicts: true
cleanPrometheusOperatorObjectNames: true
alertmanager:
  ingress:
    enabled: true
    ingressClassName: internal
    hosts: ["alertmanager.${SECRET_DOMAIN}"]
    pathType: Prefix
  alertmanagerSpec:
    alertmanagerConfiguration:
      name: alertmanager
      global:
        resolveTimeout: 5m
    externalUrl: https://alertmanager.${SECRET_DOMAIN}
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          resources:
            requests:
              storage: 1Gi
kubeEtcd:
  service:
    selector:
      component: kube-apiserver # etcd runs on control plane nodes
kubeProxy:
  enabled: false
prometheus:
  ingress:
    enabled: true
    ingressClassName: internal
    hosts: ["prometheus.${SECRET_DOMAIN}"]
    pathType: Prefix
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    enableAdminAPI: true
    walCompression: true
    enableFeatures:
      - memory-snapshot-on-shutdown
    retention: 2d
    retentionSize: 1GB
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          resources:
            requests:
              storage: 1Gi
prometheus-node-exporter:
  fullnameOverride: node-exporter
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: kubernetes_node
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[*]
    - persistentvolumeclaims=[*]
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_name"]
          targetLabel: kubernetes_node
grafana:
  enabled: true
