apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NxbmLnnMusUpxA==,iv:Xr5wTQhX4b8Bv+cnHSX2HEi8mwCKTOfHyh8RpRjfMFw=,tag:05Gf3iv8RaqgdyZRpZ1QDg==,type:str]
sops:
  age:
    - recipient: age1u7f7jaaq9x8ju7zdxf74scu8xg5ulwhlwy72lzppq5hhuxthc50stmx7m4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa3c4Y21CYlpVMTFKVXFS
        dWM1eUxIMXRVdGJVUFk2QytYUlVIdGREZUE0ClNENG9pUlgyWnRzZkRZSlh2MEZK
        MWk2ZktpM2N5VFQ1YlhuSWhtcnJ2MU0KLS0tIGFPcStkRHBoTTJ0WlpqWXpTUEY0
        dXJIcHNsMUZxYVlkY3Q3VHBaTEFJL00KkKxoTXG+Uj7Priqs0ipHHdaBMaSUQAPI
        uPG1a2m2fm3kSZpzL8yg8AwiSktoqcexaO+cHk7XamXmL6I21Xnx3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-03T18:38:41Z"
  mac: ENC[AES256_GCM,data:PCFanCNy121UyHnuS2ejvaIs8E7eZZ9hxfdVuES6990Soqzcc7xj0TUXhmqDOuB3dyY17qkw9+E3JWDMgYMFsfST1DAOZINJ4yC/jzWEOOQqX0lAcFngnj5O5jcrA8qrLoA/anT7C+Rzl93oJKP21vQaCuIknY98JSHEIsvZzr0=,iv:n0JcGbY86TJWPQzX7q4oonbOvvmcsCrACj8YJ5ykUWg=,tag:wTD1hjfHHxIf82FD6tP6bw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
